[package]
authors = ["Ben Askew-Gale <bengale2007@googlemail.com>"]
name = "genesis-brain"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
thiserror = "1.0.37"
genesis-util = {path = "../genesis-util/"}
rayon = "1.6.0"
