[package]
authors = ["Ben Askew-Gale <bengale2007@googlemail.com>"]
name = "genesis-util"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
rand = "0.8.5"
thiserror = "1.0.37"
nalgebra = "0.31.4"
glam = "0.22.0"
ndarray = "0.15.6"
