[package]
authors = ["Ben Askew-Gale <bengale2007@googlemail.com>"]
name = "genesis"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/BenGale93/genesis"
readme = "./README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.htm

[[bin]]
name = "genesis"
path = "src/bin/genesis/main.rs"

[lib]
name = "genesis"
path = "src/lib.rs"

[dependencies]
genesis-brain = { path = "crates/genesis-brain" }
genesis-genome = { path = "crates/genesis-genome" }
genesis-math = { path = "crates/genesis-math" }
anyhow = "1.0.58"
bevy = { version = "0.7.0", features = [] }
rand = "0.8.5"
thiserror = "1.0.31"

[workspace]
members = ["crates/*"]
