[package]
authors = ["Ben Askew-Gale <bengale2007@googlemail.com>"]
name = "genesis"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/BenGale93/genesis"
readme = "./README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.htm

[[bin]]
name = "genesis"
path = "src/main.rs"

[lib]
name = "genesis"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.58"
bitvec = "1.0.0"
rand = "0.8.5"
rand_distr = "0.4.3"
thiserror = "1.0.31"
