[package]
authors = ["Ben Askew-Gale <bengale2007@googlemail.com>"]
name = "genesis_maths"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
thiserror = {workspace = true}
nalgebra = {workspace = true}
glam = {workspace = true}
num = {workspace = true}
