[package]
authors = ["Ben Askew-Gale <bengale2007@googlemail.com>"]
name = "genesis_macros"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
quote = { workspace = true}
syn = { workspace = true}
proc-macro2 = { workspace = true}
