start_num = 10
minimum_number = 5
initial_synapse_count = 3
mutations = 3
start_energy = 800
lowest_energy_limit = 600
rotation_cost = [
    0.02,
    0.1,
]
translation_cost = [
    0.02,
    0.1,
]
unit_size_cost = 0.02
world_energy = 30000
plant_energy_per_unit = 2
plant_size_range = [
    10.0,
    30.0,
]
mutation_probability = 0.02
cost_of_thought = 0.002

[[spawners]]
centre = [
    0.0,
    0.0,
]
radius = 500.0

[spawners.dist]
name = 'normal'
a = 0.0
b = 1.0

[attributes]
hatch_age = [
    10.0,
    30.0,
    15,
]
max_speed = [
    100.0,
    500.0,
    100,
]
max_rotation = [
    10.0,
    30.0,
    20,
]
eye_range = [
    200.0,
    700.0,
    100,
]
cost_of_eating = [
    0.2,
    0.3,
    10,
]
offspring_energy = [
    0.5,
    1.0,
    100,
]
max_size = [
    80.0,
    100.0,
    20,
]
growth_rate = [
    0.05,
    0.1,
    20,
]

[dependent_attributes]
adult_age_bounds = [
    30.0,
    60.0,
]
death_age_bounds = [
    400.0,
    600.0,
]
eye_angle_bounds = [
    60.0,
    330.0,
]
mouth_width_bounds = [
    30.0,
    90.0,
]
hatch_size_bounds = [
    20.0,
    35.0,
]
