start_num = 0
minimum_number = 0
energy_floor = 2000
initial_synapse_count = 3
mutations = 3
start_energy = 300
lowest_energy_limit = 600
max_rotation = 15.0
rotation_cost = 0.015
max_translation = 400.0
translation_cost = 0.015
unit_size_cost = 0.02
world_energy = 100000
plant_energy_per_unit = 2
plant_size_range = [
    10.0,
    30.0,
]
plant_density = 10.0
mutation_probability = 0.1
cost_of_thought = 0.008
cost_of_grab = 0.02

[[spawners]]
centre = [
    0.0,
    0.0,
]
radius = 700.0

[spawners.dist]
name = 'gamma'
a = 2.0
b = 2.0

[[spawners]]
centre = [
    0.0,
    -16000.0,
]
radius = 7000.0

[spawners.dist]
name = 'uniform'
a = -1.0
b = 1.0

[attributes]
hatch_age = [
    10.0,
    30.0,
    15,
]
eye_range = [
    200.0,
    700.0,
    100,
]
cost_of_eating = [
    0.2,
    0.3,
    10,
]
offspring_energy = [
    0.5,
    1.0,
    100,
]
max_size = [
    80.0,
    100.0,
    20,
]
growth_rate = [
    0.05,
    0.1,
    20,
]
grab_angle = [
    30.0,
    60.0,
    10,
]

[dependent_attributes]
adult_age_bounds = [
    30.0,
    60.0,
]
death_age_bounds = [
    400.0,
    600.0,
]
eye_angle_bounds = [
    60.0,
    330.0,
]
mouth_width_bounds = [
    30.0,
    90.0,
]
hatch_size_bounds = [
    20.0,
    35.0,
]
grab_strength_bounds = [
    0.01,
    0.05,
]

[brain_mutations]
deactivate_neuron = 0.1
add_neuron = 0.1
neuron_bias = 0.05
activation_func = 0.05
synapse_weight = 0.5
deactivate_synapse = 0.1
add_synapse = 0.1
