start_num = 20
minimum_number = 0
energy_floor = 200000
initial_synapse_count = 3
mutations = 3
start_energy = 30000
lowest_energy_limit = 60000
max_rotation = 15.0
rotation_cost = 1.5
max_translation = 400.0
translation_cost = 1.5
unit_size_cost = 2.0
world_energy = 1000000
mutation_probability = 0.1
cost_of_thought = 0.8
cost_of_grab = 2.0
cost_of_lay = 5.0

[plant]
energy_density = 200
toughness = 5.0
size_range = [
    10.0,
    30.0,
]
density = 10.0

[meat]
energy_density = 400
toughness = 2.0
density = 5.0

[[spawners]]
centre = [
    0.0,
    0.0,
]
radius = 500.0

[spawners.dist]
name = 'normal'
a = 0.0
b = 1.0

[attributes]
hatch_age = [
    10.0,
    30.0,
    15,
]
eye_range = [
    200.0,
    700.0,
    100,
]
cost_of_eating = [
    0.2,
    0.3,
    10,
]
offspring_energy = [
    0.5,
    1.0,
    100,
]
max_size = [
    80.0,
    100.0,
    20,
]
growth_rate = [
    0.05,
    0.1,
    20,
]
grab_angle = [
    30.0,
    60.0,
    10,
]

[dependent_attributes]
adult_age_bounds = [
    30.0,
    60.0,
]
death_age_bounds = [
    400.0,
    600.0,
]
eye_angle_bounds = [
    60.0,
    330.0,
]
mouth_width_bounds = [
    30.0,
    90.0,
]
hatch_size_bounds = [
    20.0,
    35.0,
]
grab_strength_bounds = [
    0.01,
    0.05,
]

[brain_mutations]
deactivate_neuron = 0.1
add_neuron = 0.1
neuron_bias = 0.05
activation_func = 0.05
synapse_weight = 0.5
deactivate_synapse = 0.1
add_synapse = 0.1
