[package]
authors = ["Ben Askew-Gale <bengale2007@googlemail.com>"]
name = "genesis-genome"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
rand = "0.8.5"
thiserror = "1.0.31"
bitvec = "1.0.1"
genesis-util = {path = "../genesis-util/"}
ndarray = "0.15.6"
