[package]
authors = ["Ben Askew-Gale <bengale2007@googlemail.com>"]
name = "genesis-math"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
thiserror = "1.0.32"
nalgebra = "0.31.1"
bevy_transform = "0.8.0"
