[package]
authors = ["Ben Askew-Gale <bengale2007@googlemail.com>"]
name = "genesis_newtype"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
rand = {workspace = true}
thiserror = {workspace = true}
serde_derive = { workspace = true}
serde = { workspace = true}
