name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    name: "build & test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: actions-rs/toolchain@latest
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: Swatinem/rust-cache@latest
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: g++ pkg-config libx11-dev libasound2-dev libudev-dev libgtk-3-dev
          version: 1.0
      - run: cargo build --all
      - run: cargo test --all

  cargo-fmt:
    name: "cargo fmt"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: actions-rs/toolchain@latest
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - run: cargo fmt --all --check

  cargo_clippy:
    name: "cargo clippy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: actions-rs/toolchain@latest
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@latest
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: g++ pkg-config libx11-dev libasound2-dev libudev-dev libgtk-3-dev
          version: 1.0
      - run: cargo clippy --all --all-targets --all-features
