name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  full:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: sudo apt install g++ pkg-config libx11-dev libasound2-dev libudev-dev
      - name: Update
        run: rustup update nightly && rustup default nightly
      - name: Add components
        run: rustup component add rustfmt clippy
      - name: Run fmt
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all --all-targets --all-features
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
